export enum ROLESMODEL {
  VIEWER = "VIEWER",
  EDITOR = "EDITOR",
  OWNER = "OWNER",
}

export enum STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum CONTENT_STATUS {
  IDEA = "IDEA",
  DRAFT = "DRAFT",
  REVIEW = "REVIEW",
  APPROVED = "APPROVED",
  PUBLISHED = "PUBLISHED",
  REJECTED =   "REJECTED",
}